# Пользователи
## Создание нового пользователя

POST http://localhost:3000/users/register/ HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "name": "Mikhail",
  // avatarPath: 'mikhail.jpg',
  "userType": "обычный",
  "password": "123456"
}

###

## Вход в закрытую часть приложения

POST http://localhost:3000/users/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "example@email.ru",
  "password": "123456"
}

###

## Завершения пользовательского сеанса.

POST  http://localhost:3000/users/logout/ HTTP/1.1
Content-Type: application/json

{}

###

## Проверка состояния пользователя.

GET  http://localhost:3000/users/check_auth/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImV4YW1wbGVAZW1haWwucnUiLCJuYW1lIjoiTWlraGFpbCIsImlkIjoiNjVkNjQwOGRlOGVlYjhjZTY0YTgwMjJjIiwiaWF0IjoxNzA4NjAxOTM3LCJleHAiOjE3MDg2ODgzMzd9.xSO_u4IQbli5Kr68_BS70PETPvG-LmDpWPkJ0-8JSbU


###

## Отправить изображение

POST http://localhost:3000/users/65d0a425f9edd529dc99adf1/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\User\Downloads\1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
