# Офферы
## Создание нового предложения

POST http://localhost:3000/offers/ HTTP/1.1
Content-Type: application/json

{
  "title": "Luxury Apartment",
  "description": "Spacious apartment with a great view",
  "city": "Paris",
  "previewImage": "example-path.png",
  "listImages": [
    "example-path.png",
    "example-path.png",
    "example-path.png",
    "example-path.png",
    "example-path.png",
    "example-path.png"
  ],
  "isPremium": false,
  "houseType": "room",
  "rooms": 1,
  "guests": 1,
  "rentalCost": 100,
  "amenities": [
    "Baby seat",
    "Washer",
    "Towels"
  ],
  "latitude": 48.85661,
  "longitude": 2.351499,
  "userId": "65cc6fedc049de8eacfec48d"
}

###

## Детальная информация по предложению.

GET  http://localhost:3000/offers/65cc71e3fdd05465bf06e158/ HTTP/1.1
Content-Type: application/json

###
