# Комментарии
## Добавление комментария

POST http://localhost:3000/comments/65d0995c44cbfa2d5c482902/ HTTP/1.1
Content-Type: application/json

{
  "text": "qwerty test",
  "rating": 3,
  "offerId": "65d0995c44cbfa2d5c482902",
  "userId": "65ccc7c8f513b1be9d11770d"
}

###
